version: '2'

networks:
  tig:
  telegraf:

services:
  influxdb:
    image: influxdb:1.7.2
    container_name: influxdb
    environment:
      INFLUXDB_USERNAME: "admin"
      INFLUXDB_PASSWORD: "pass"
    expose:
      - 8086
      - 8083
    networks:
      - tig

  telegraf:
    image: telegraf:1.9.1
    container_name: telegraf
    volumes:
      - $PWD/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - "influxdb"
    networks:
      - tig
      - telegraf

  grafana:
    image: grafana/grafana:5.4.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - $PWD/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
      - $PWD/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
      - $PWD/grafana/dashboards:/var/tmp/dashboards
    depends_on:
      - "telegraf"
    networks:
      - tig

  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    expose: 
      - 27017
    networks: 
      - telegraf

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch
    expose: 
      - 9200
    ports: 
      - "19200:9200"
    environment:
      discovery.type: single-node
    